version: '2.4'

services:
    nginx:
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./static/:/usr/share/nginx/html:ro
        restart: always
        stop_grace_period: 0s
    robear:
        build: .
        restart: always
        stop_grace_period: 0s
